// Build the interview / cover-letter summary document from outputs/summary_data.json
// (generated by src/generate_docx_data.py). Run: node scripts/build_summary_docx.js
const fs = require("fs");
const path = require("path");
const {
  Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell,
  WidthType, ShadingType, BorderStyle, AlignmentType,
} = require("docx");

const ROOT = path.resolve(__dirname, "..");
const DATA_PATH = path.join(ROOT, "outputs", "summary_data.json");
const OUT_PATH = path.join(ROOT, "outputs", "credit_risk_scorecard_summary.docx");

const data = JSON.parse(fs.readFileSync(DATA_PATH, "utf-8"));

const pct = (v, digits = 2) => `${(v * 100).toFixed(digits)}%`;
const num = (v, digits = 4) => Number(v).toFixed(digits);

const MODEL_LABEL = { logistic_woe: "로지스틱 회귀 (WoE 스코어카드, 베이스라인)", lightgbm: "LightGBM (고도화 모델)" };

const TABLE_WIDTH = 9000; // DXA

function headerCell(text, width) {
  return new TableCell({
    width: { size: width, type: WidthType.DXA },
    shading: { type: ShadingType.CLEAR, fill: "E8EEF9" },
    children: [new Paragraph({ children: [new TextRun({ text, bold: true })] })],
  });
}

function cell(text, width) {
  return new TableCell({
    width: { size: width, type: WidthType.DXA },
    children: [new Paragraph({ text })],
  });
}

function metricsTable() {
  const w = [4200, 1600, 1600, 1600];
  return new Table({
    width: { size: TABLE_WIDTH, type: WidthType.DXA },
    columnWidths: w,
    rows: [
      new TableRow({ children: [headerCell("모델", w[0]), headerCell("AUC", w[1]), headerCell("KS", w[2]), headerCell("Gini", w[3])] }),
      new TableRow({ children: [
        cell(MODEL_LABEL[data.baseline.model_type], w[0]),
        cell(num(data.baseline.auc), w[1]), cell(num(data.baseline.ks), w[2]), cell(num(data.baseline.gini), w[3]),
      ] }),
      new TableRow({ children: [
        cell(MODEL_LABEL[data.advanced.model_type], w[0]),
        cell(num(data.advanced.auc), w[1]), cell(num(data.advanced.ks), w[2]), cell(num(data.advanced.gini), w[3]),
      ] }),
    ],
  });
}

function gradeTable() {
  const order = ["A", "B", "C", "D", "E"];
  const w = [1500, 2500, 2500, 2500];
  const rows = [new TableRow({ children: [headerCell("등급", w[0]), headerCell("인원수", w[1]), headerCell("평균 점수", w[2]), headerCell("실제 부도율", w[3])] })];
  for (const g of order) {
    const s = data.grade_stats[g];
    if (!s) continue;
    rows.push(new TableRow({ children: [
      cell(g, w[0]), cell(s.count.toLocaleString(), w[1]), cell(s.avg_score.toFixed(1), w[2]), cell(pct(s.default_rate), w[3]),
    ] }));
  }
  return new Table({ width: { size: TABLE_WIDTH, type: WidthType.DXA }, columnWidths: w, rows });
}

function h1(text) { return new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 150 } }); }
function h2(text) { return new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 100 } }); }
function body(text) { return new Paragraph({ children: [new TextRun(text)], spacing: { after: 120 } }); }
function bullet(text) { return new Paragraph({ text, bullet: { level: 0 }, spacing: { after: 80 } }); }

const championLabel = MODEL_LABEL[data.champion];
const aucGainPct = (data.auc_gain * 100).toFixed(2);
const cutoff = data.cutoff_50;
const ivNames = data.iv_top.map((r) => r.feature_name).join(", ");
const gradeRatio = data.grade_default_ratio_e_over_a ? data.grade_default_ratio_e_over_a.toFixed(1) : "N/A";
const psiText = data.psi_score ? `${data.psi_score.psi_value.toFixed(4)} (train↔test, ${data.psi_score.psi_value < 0.1 ? "안정" : "변화 감지"})` : "N/A";

const doc = new Document({
  sections: [
    {
      properties: {},
      children: [
        new Paragraph({ text: "Credit Risk Scorecard 프로젝트 요약", heading: HeadingLevel.TITLE, spacing: { after: 100 } }),
        new Paragraph({
          children: [new TextRun({ text: "Home Credit Default Risk 기반 여신심사 스코어카드 파이프라인 · 자소서/면접용 요약", italics: true, color: "555555" })],
          spacing: { after: 300 },
        }),

        h1("1. 프로젝트 개요"),
        body(
          `Kaggle의 Home Credit Default Risk 데이터(${data.n_applicants.toLocaleString()}건)를 사용해, 실제 여신심사 업무 흐름을 ` +
          "변수처리 → WoE/IV 스코어카드 → 고도화 모델 → 등급설계 → 컷오프 시뮬레이션 → 안정성/해석까지 " +
          "엔드투엔드로 재현한 개인 프로젝트입니다. 전처리부터 리포트 생성까지 run.py 한 번으로 자동 실행되며, " +
          "모든 결과는 SQL로 조회 가능한 SQLite에 저장하고 Streamlit 대시보드로 인터랙티브하게 확인할 수 있습니다."
        ),

        h1("2. 핵심 성과 지표"),
        body(`IV(Information Value) 기준(0.02~0.5)으로 ${data.iv_top.length}개 이상 변수 중 상위 변수(${ivNames} 등)를 선별해 스코어카드를 구성했습니다.`),
        metricsTable(),
        new Paragraph({ text: "", spacing: { after: 200 } }),

        h1("3. 챔피언-챌린저 판단"),
        body(
          `단순히 성능이 더 높은 모델을 채택하지 않고, 사전에 정의한 임계값(AUC +0.01pt)을 기준으로 판단했습니다. ` +
          `LightGBM이 베이스라인 로지스틱 스코어카드 대비 AUC를 +${aucGainPct}%p(절대값 ${num(data.auc_gain)}) 개선했고, ` +
          `이는 기준치를 상회하여 "${championLabel}"을 챔피언 모델로 채택했습니다. ` +
          "기준에 미달했다면 해석 가능성이 높은 로지스틱 스코어카드를 유지하는 방향으로 설계했습니다."
        ),

        h1("4. 신용 등급 설계 및 비즈니스 임팩트"),
        body("PDO(Points to Double Odds) 방식으로 확률을 점수로 스케일링하고, 동일 인원수 기준 A~E 5등급을 설계했습니다."),
        gradeTable(),
        new Paragraph({ text: "", spacing: { after: 200 } }),
        body(
          gradeRatio !== "N/A"
            ? `A등급과 E등급의 실제 부도율 차이는 약 ${gradeRatio}배로, 등급 체계가 실제 위험도를 잘 분리하고 있음을 확인했습니다.`
            : "등급 체계가 실제 위험도를 잘 분리하고 있음을 확인했습니다."
        ),

        h1("5. 컷오프 시뮬레이션 인사이트"),
        body(
          cutoff
            ? `컷오프 점수 ${cutoff.cutoff.toFixed(1)}점(승인율 ${pct(cutoff.approval_rate, 0)}) 기준, 예상 부도율 ${pct(cutoff.expected_default_rate)}, ` +
              `예상 손실률 ${pct(cutoff.expected_loss)}(LGD 45% 가정)로 나타났습니다. 승인율과 리스크 간 트레이드오프를 ` +
              "정량적으로 제시해, 심사 정책 결정에 바로 활용 가능한 형태로 구성했습니다."
            : "컷오프별 승인율/부도율/손실률 트레이드오프를 정량적으로 제시했습니다."
        ),

        h1("6. 모델 안정성 점검 (PSI)"),
        body(`Train/Test 간 스코어 분포 PSI = ${psiText}. 표준 해석 기준(<0.1 안정)에 따라 모델이 데이터 분포 변화에 안정적임을 정량적으로 검증했습니다.`),

        h1("7. 사용 기술 스택"),
        bullet("Python: pandas, scikit-learn, LightGBM, SHAP"),
        bullet("SQLite: WoE/IV, 모델 성능, 스코어, 컷오프 시뮬레이션, PSI 결과 저장 및 SQL 조회"),
        bullet("Streamlit + Plotly: 컷오프 시뮬레이션 인터랙티브 대시보드"),
        bullet("pytest: WoE/IV, 점수 스케일링 함수 단위테스트"),

        h1("8. 자소서용 요약 문단 (복사해서 활용)"),
        new Paragraph({
          border: { left: { style: BorderStyle.SINGLE, size: 12, color: "2A78D6" } },
          indent: { left: 200 },
          spacing: { before: 100, after: 100 },
          children: [new TextRun({
            text:
              `Home Credit Default Risk 데이터 ${data.n_applicants.toLocaleString()}건을 활용해 여신심사 스코어카드 파이프라인을 ` +
              `직접 설계·구현했습니다. WoE/IV 기반 변수 선별로 로지스틱 베이스라인 스코어카드(AUC ${num(data.baseline.auc)})를 만들고, ` +
              `LightGBM으로 고도화하여 AUC ${num(data.advanced.auc)}(+${aucGainPct}%p)를 달성했습니다. 단순 성능 비교가 아니라 ` +
              "사전에 정의한 채택 기준에 따라 챔피언 모델을 결정했고, PDO 점수 스케일링과 A-E 등급 설계, 컷오프 시뮬레이션으로 " +
              "승인율-리스크 트레이드오프를 정량화했으며, PSI로 모델 안정성까지 점검해 실무 여신심사 프로세스를 엔드투엔드로 재현했습니다.",
          })],
        }),

        h1("9. 예상 면접 질문 & 답변 포인트"),
        h2("Q. 로지스틱 회귀와 LightGBM을 둘 다 만든 이유는?"),
        body("해석 가능성이 중요한 여신심사 도메인 특성상, 성능만으로 모델을 정하지 않고 '챔피언-챌린저' 방식으로 두 모델을 비교해 사전 정의된 기준으로 객관적으로 판단하기 위함입니다."),
        h2("Q. IV 기준으로 변수를 선택한 이유는?"),
        body("IV<0.02는 예측력이 거의 없고, IV>0.5는 데이터 누수(leakage) 의심 신호라는 스코어카드 업계 표준 기준을 적용해 변수를 객관적으로 스크리닝했습니다."),
        h2("Q. PSI는 왜 중요한가요?"),
        body("모델이 배포된 이후 시간이 지나며 입력 데이터 분포가 변하면(Population Shift) 성능이 저하될 수 있어, PSI로 이 변화를 정량적으로 모니터링해 재학습 시점을 판단하는 데 씁니다."),
        h2("Q. 실제 여신심사에서 이 결과를 어떻게 활용할 수 있나요?"),
        body("컷오프 시뮬레이션 표를 통해 원하는 승인율에서의 예상 부도율/손실률을 미리 파악할 수 있어, 리스크 허용 수준에 맞는 컷오프를 데이터 기반으로 설정하는 데 직접 활용할 수 있습니다."),
      ],
    },
  ],
});

Packer.toBuffer(doc).then((buffer) => {
  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, buffer);
  console.log(`Wrote ${OUT_PATH}`);
});
